.PHONY: all

all:
	make -C hw-syllabus
	make -C hw-0
	make -C hw-1/plan
	make -C hw-2/plan
	make -C sw-syllabus
	make -C hw-3/worksheet
	make -C	hw-4
	make -C sw-1
	make -C sw-2/ws
	make -C sw-5/k-means-ws
